import {createRequire} from 'node:module';
import test from 'node:test';import assert from 'node:assert/strict';import {generateKeyPairSync,sign} from 'node:crypto';import {EventEmitter} from 'node:events';import {validateReleasePolicy,validateUpdateInfo,createUpdateController} from './update-controller.mjs';
// Disposable generated test keys never sign real artifacts and are not release credentials.
const keys=generateKeyPairSync('ed25519'),other=generateKeyPairSync('ed25519');
const policy={approved:true,activated:true,provider:'github',owner:'endlessblink',repo:'rough-cut',url:'https://github.com/endlessblink/rough-cut/releases/',channel:'beta',publisherPublicKey:keys.publicKey.export({type:'spki',format:'pem'})};
const opts={currentVersion:'0.1.0-beta.6',feedURL:policy.url,provider:'github',publisherPublicKey:policy.publisherPublicKey};
const signed=(changes={},key=keys.privateKey)=>{const info={version:'0.1.0-beta.7',files:[{url:'Rough-Cut.AppImage',sha512:Buffer.alloc(64,1).toString('base64')}],...changes};const payload=Buffer.from(JSON.stringify({version:info.version,platform:'linux',arch:'x64',files:info.files.map(({url,sha512})=>({url,sha512}))}));return {...info,publisherSignature:sign(null,payload,key).toString('base64')};};
test('owner-approved destination is configured but activation remains fail-closed',()=>{assert.equal(validateReleasePolicy({...policy,activated:false,publisherPublicKey:null}),null);assert.ok(validateReleasePolicy(policy));assert.throws(()=>validateReleasePolicy({...policy,publisherPublicKey:null}));for(const changes of [{owner:'someone'},{repo:'other'},{url:'https://github.com/endlessblink/rough-cut/releases/?token=x'},{channel:'latest'}])assert.throws(()=>validateReleasePolicy({...policy,...changes}));});
test('valid signed asset basename accepted',()=>{assert.ok(validateUpdateInfo(signed(),opts));});
test('unsigned, wrong-key and tampered metadata rejected',()=>{const info=signed();assert.throws(()=>validateUpdateInfo({...info,publisherSignature:undefined},opts));assert.throws(()=>validateUpdateInfo(signed({},other.privateKey),opts));assert.throws(()=>validateUpdateInfo({...info,version:'0.1.0-beta.8'},opts));assert.throws(()=>validateUpdateInfo({...info,publisherSignature:'x'},opts));});
test('signed metadata cannot authorize untrusted paths, credentials, fragments or non-AppImage',()=>{for(const url of ['https://github.com/endlessblink/rough-cut/releases/download/v0.1.0-beta.7/a.AppImage','https://github.com/other/rough-cut/releases/download/v0.1.0-beta.7/a.AppImage','https://github.com/endlessblink/rough-cut/releases/download/v0.1.0-beta.8/a.AppImage','../a.AppImage','a.AppImage?x=1','a.deb','https://evil.test/a.AppImage','https://user:pass@github.com/endlessblink/rough-cut/releases/download/v0.1.0-beta.7/a.AppImage'])assert.throws(()=>validateUpdateInfo(signed({files:[{url,sha512:Buffer.alloc(64,1).toString('base64')}]}),opts));});
test('old version, tag mismatch and malformed checksum rejected',()=>{assert.throws(()=>validateUpdateInfo(signed({version:'0.1.0-beta.5'}),opts));assert.throws(()=>validateUpdateInfo(signed({tag:'v0.1.0-beta.8'}),opts));assert.throws(()=>validateUpdateInfo(signed({files:[{url:'a.AppImage',sha512:'bad'}]}),opts));});
test('unsigned metadata prevents download and install; GitHub provider is exact and token-free',async()=>{const backend=new EventEmitter();let downloads=0,feed;backend.setFeedURL=p=>feed=p;backend.checkForUpdates=async()=>({updateInfo:{version:'0.1.0-beta.7',files:[{url:'a.AppImage',sha512:Buffer.alloc(64,1).toString('base64')}]}});backend.downloadUpdate=async()=>downloads++;const c=createUpdateController({backend,releasePolicy:policy,appImagePath:'/tmp/test-only-not-written.AppImage',userDataDir:'/tmp',version:opts.currentVersion});assert.equal((await c.check()).status,'error');assert.equal(downloads,0);assert.equal(c.install().status,'not-ready');assert.deepEqual(feed,{provider:'github',owner:'endlessblink',repo:'rough-cut',private:false,channel:'beta'});});

test('installed GitHubProvider resolves signed basename to exact owned release without network',()=>{const require=createRequire(import.meta.url);const {GitHubProvider}=require('electron-updater/out/providers/GitHubProvider');const provider=new GitHubProvider({provider:'github',owner:'endlessblink',repo:'rough-cut'}, {channel:'beta',allowPrerelease:true}, {platform:'linux',executor:{}});const info=signed({tag:'v0.1.0-beta.7'});validateUpdateInfo(info,opts);const files=provider.resolveFiles(info);assert.equal(files[0].url.href,'https://github.com/endlessblink/rough-cut/releases/download/v0.1.0-beta.7/Rough-Cut.AppImage');});

test('inactive approved GitHub policy explains activation gate accurately',async()=>{const c=createUpdateController({releasePolicy:{...policy,activated:false,publisherPublicKey:null},appImagePath:'/tmp/no-install.AppImage',userDataDir:'/tmp',version:opts.currentVersion});const state=await c.check();assert.equal(state.status,'disabled');assert.match(state.reason,/inactive.*signed-release.*install\/rollback acceptance/);});
